# Generated by Django 2.2.3 on 2019-07-17 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeatInfo',
            new_name='Screen',
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3, null=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Screen')),
            ],
        ),
    ]
