# Generated by Django 2.2.3 on 2019-07-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190718_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
