# Generated by Django 2.2.3 on 2019-07-17 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_seat_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='avilable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Seat')),
            ],
        ),
    ]
